DROP TABLE IF EXISTS training.shiritori;

CREATE TABLE training.shiritori (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    entry varchar(30) NOT NULL,
    word varchar(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci;